### ISSUE TITLE
W/System.err: java.io.IOException: read failed, socket might closed or timeout, read ret: -1

### ISSUE THREAD

**Issue by amitsharmarepos** [imrankst1221/Thermal-Printer-in-Android#18]
Hello Imran,

Thanks for your your solution. Please do let me know what is the issue 

02-20 14:22:43.443 29100-29229/infixsoft.imrankst1221.printer W/BluetoothAdapter: getBluetoothService() called with no BluetoothManagerCallback
02-20 14:22:43.686 29100-29229/infixsoft.imrankst1221.printer W/System.err: java.io.IOException: read failed, socket might closed or timeout, read ret: -1
        at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:740)
        at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:752)
        at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:374)
        at infixsoft.imrankst1221.printer.DeviceList$2.run(DeviceList.java:245)
02-20 14:22:43.687 29100-29229/infixsoft.imrankst1221.printer W/System.err:     at java.lang.Thread.run(Thread.java:818)

Please do let me the solution.
Thanks
Amit

**Comment by helloail** [comment]
same with me

**Comment by helloail** [comment]
> Hello Imran,
> 
> Thanks for your your solution. Please do let me know what is the issue
> 
> 02-20 14:22:43.443 29100-29229/infixsoft.imrankst1221.printer W/BluetoothAdapter: getBluetoothService() called with no BluetoothManagerCallback
> 02-20 14:22:43.686 29100-29229/infixsoft.imrankst1221.printer W/System.err: java.io.IOException: read failed, socket might closed or timeout, read ret: -1
> at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:740)
> at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:752)
> at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:374)
> at infixsoft.imrankst1221.printer.DeviceList$2.run(DeviceList.java:245)
> 02-20 14:22:43.687 29100-29229/infixsoft.imrankst1221.printer W/System.err: at java.lang.Thread.run(Thread.java:818)
> 
> Please do let me the solution.
> Thanks
> Amit

Did you fix this issue
